// Generated by the Project2023 Bot on 2023-05-17 at 18:48:36 UTC+00:00

package main

import (
	"fmt"
	"math/rand"
)

func main() {
	// Random integer between 1 and 10
	randomInt := rand.Intn(9)+1
	fmt.Println("Random integer:", randomInt)
}
